// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRUN-V0h3kImlg6ahsIavkwgXBAsipiAQ',
    appId: '1:218963153959:web:a60f22ec81b1c454446a02',
    messagingSenderId: '218963153959',
    projectId: 'webapp-e5f8c',
    authDomain: 'webapp-e5f8c.firebaseapp.com',
    storageBucket: 'webapp-e5f8c.appspot.com',
    measurementId: 'G-ZJGKY3G3SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcbO8i5OYfj3MmAFgNTWiD1O4PFch1wo',
    appId: '1:218963153959:android:d6731060778455eb446a02',
    messagingSenderId: '218963153959',
    projectId: 'webapp-e5f8c',
    storageBucket: 'webapp-e5f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-6W2plPjOsCn5yhd0Fx-aULfY3Oxefk',
    appId: '1:218963153959:ios:34f34a5d09aa9c44446a02',
    messagingSenderId: '218963153959',
    projectId: 'webapp-e5f8c',
    storageBucket: 'webapp-e5f8c.appspot.com',
    iosClientId: '218963153959-je4764b0car44itieoqucnaq5vgk2qfb.apps.googleusercontent.com',
    iosBundleId: 'com.levi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-6W2plPjOsCn5yhd0Fx-aULfY3Oxefk',
    appId: '1:218963153959:ios:e0ac72816fd1ad8a446a02',
    messagingSenderId: '218963153959',
    projectId: 'webapp-e5f8c',
    storageBucket: 'webapp-e5f8c.appspot.com',
    iosClientId: '218963153959-m9pd6v8insid52lrf8fk29iiqdmlem5u.apps.googleusercontent.com',
    iosBundleId: 'com.levi.app.RunnerTests',
  );
}
